apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: joshlong-authorization-api
  name: joshlong-authorization-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joshlong-authorization-api
  template:
    metadata:
      labels:
        app: joshlong-authorization-api
    spec:
      containers:
        - image: gcr.io/pgtm-jlong/joshlong-authorization-api
          imagePullPolicy: Always
          name: joshlong-authorization-api

          startupProbe:
            failureThreshold: 100
            periodSeconds: 10
            httpGet:
              port: 8443
              path: /actuator/health/readiness

          readinessProbe:
            failureThreshold: 100
            periodSeconds: 10
            httpGet:
              port: 8443
              path: /actuator/health/readiness

          livenessProbe:
            failureThreshold: 100
            periodSeconds: 10
            httpGet:
              port: 8443
              path: /actuator/health/liveness

          envFrom:
            - secretRef:
                name: joshlong-authorization-api-secrets

          env:
            - name: SPRING_SECURITY_OAUTH2_AUTHORIZATIONSERVER_ISSUER
              value : "https://authorization.joshlong.com"
            - name: SPRING_SECURITY_OAUTH2_AUTHORIZATIONSERVER_CLIENT_CLIENT_1_REGISTRATION_REDIRECT_URIS
              value : "https://studio.twis.online/login/oauth2/code/spring"
            - name: SERVER_PORT
              value: "8443"
            - name: LANG
              value: "en_US.UTF-8"

          ports:
            - containerPort: 8443

          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"