apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: joshlong-api
  name: joshlong-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joshlong-api
  template:
    metadata:
      labels:
        app: joshlong-api
    spec:
      containers:
        - image: gcr.io/pgtm-jlong/joshlong-api
          imagePullPolicy: Always
          name: joshlong-api

          startupProbe:
            failureThreshold: 240
            periodSeconds: 240
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          readinessProbe:
            failureThreshold: 240
            periodSeconds: 240
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          livenessProbe:
            failureThreshold: 240
            periodSeconds: 240
            httpGet:
              port: 8080
              path: /actuator/health/liveness

          envFrom:
            - secretRef:
                name: joshlong-api-secrets

          env:
            - name: BLOG_RESET_ON_REBUILD
              value: "true"
            - name: BLOG_API_SERVER_URI
              value: "https://api.joshlong.com"
            - name: LANG
              value: "en_US.UTF-8"

          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "2Gi"